name: go-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: go-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ "1.23" ]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: mocks
        run: make generate

      - name: Setup go modules
        run: go clean -modcache;go mod tidy; go mod download; go mod verify;

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=5m --modules-download-mode=readonly
          skip-pkg-cache: true
          skip-build-cache: true

      - uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          # Description: Path to compose file(s). It can be a list of files. It can be
          # absolute or relative to the current working directory (cwd).
          #
          # Default: ./docker-compose.yml
          compose-file: docker-compose.yaml

      - name: wait for services
        run: sleep 20

      - name: Test and generate code coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1